(define size 2)
(define (square x) (* x x))
(square 2)
(square (+ 2 5))
(+ (square 2) (square 4))
(define (sum-of-squares x y)
  (+ (square x) (square y)))
(sum-of-squares 5 5)
(define (f a)
  (sum-of-squares (+ a 1) (* a 2)))
(f 2)

; 1.1.6 conditionals and predicates
(define (abs x)
  (cond ((> x 0) x)
        ((= x 0) 0)
        ((< x 0) (- x))))
(define (abs x)
  (if (< x 0) (- x) x))
(abs -1)
